name: Docker

on:
  schedule:
    - cron: '35 18 * * *'
  push:
    branches: [ "qa" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "qa" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_REPO }}

jobs:

  test:
    name: Run functional tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: PYTHONPATH=. pytest tests/test_upload_photo.py -v

  build:
    name: Build and push Docker image
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  deploy:
    name: qa upload_photo
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PEM }}
          script: |
            docker stop project_upload_photo || true
            docker rm project_upload_photo || true
            docker rmi ${{ secrets.DOCKER_REPO }}:qa || true

            docker pull ${{ secrets.DOCKER_REPO }}:qa

            docker run -d \
              --restart always \
              --name project_upload_photo \
              -p 8080:8080 \
              -e MONGO_HOSTIP=${{ secrets.MONGO_HOSTIP }} \
              -e MONGO_PORT=${{ secrets.MONGO_PORT }} \
              -e MONGO_USER=${{ secrets.MONGO_USER }} \
              -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
              -e MONGO_DB=${{ secrets.MONGO_DB }} \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              ${{ secrets.DOCKER_REPO }}:qa
